/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
export enum Platform {
  YOUTUBE = 0,
  FACEBOOK = 1,
  DAILYMOTION = 2,
  MAINSTREAM = 3,
  URL = 4,
}
export enum AssetType {
  AUDIO = 0,
  VIDEO = 1,
}
export enum Category {
  DOCUMENTARY = 0,
  EXPLAINER = 1,
  FEATURE = 2,
  NEWS = 3,
  HOSTED = 4,
  PAID = 5,
  LIVESTREAM = 6,
}
export enum PrivacyStatus {
  PRIVATE = 0,
  UNLISTED = 1,
  PUBLIC = 2,
}
