/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as __NAMESPACE__ from "./.";
export interface IBlockElement {
    type: __NAMESPACE__.ElementType;
    assets: Array<__NAMESPACE__.IAsset>;
    textTypeData?: __NAMESPACE__.ITextElementFields;
    videoTypeData?: __NAMESPACE__.IVideoElementFields;
    tweetTypeData?: __NAMESPACE__.ITweetElementFields;
    imageTypeData?: __NAMESPACE__.IImageElementFields;
    audioTypeData?: __NAMESPACE__.IAudioElementFields;
    pullquoteTypeData?: __NAMESPACE__.IPullquoteElementFields;
    interactiveTypeData?: __NAMESPACE__.IInteractiveElementFields;
    mapTypeData?: __NAMESPACE__.IStandardElementFields;
    documentTypeData?: __NAMESPACE__.IStandardElementFields;
    tableTypeData?: __NAMESPACE__.IStandardElementFields;
    witnessTypeData?: __NAMESPACE__.IWitnessElementFields;
    richLinkTypeData?: __NAMESPACE__.IRichLinkElementFields;
    membershipTypeData?: __NAMESPACE__.IMembershipElementFields;
    embedTypeData?: __NAMESPACE__.IEmbedElementFields;
    instagramTypeData?: __NAMESPACE__.IInstagramElementFields;
    commentTypeData?: __NAMESPACE__.ICommentElementFields;
    vineTypeData?: __NAMESPACE__.IVineElementFields;
    contentAtomTypeData?: __NAMESPACE__.IContentAtomElementFields;
}
export interface IBlockElementArgs {
    type: __NAMESPACE__.ElementType;
    assets: Array<__NAMESPACE__.IAssetArgs>;
    textTypeData?: __NAMESPACE__.ITextElementFieldsArgs;
    videoTypeData?: __NAMESPACE__.IVideoElementFieldsArgs;
    tweetTypeData?: __NAMESPACE__.ITweetElementFieldsArgs;
    imageTypeData?: __NAMESPACE__.IImageElementFieldsArgs;
    audioTypeData?: __NAMESPACE__.IAudioElementFieldsArgs;
    pullquoteTypeData?: __NAMESPACE__.IPullquoteElementFieldsArgs;
    interactiveTypeData?: __NAMESPACE__.IInteractiveElementFieldsArgs;
    mapTypeData?: __NAMESPACE__.IStandardElementFieldsArgs;
    documentTypeData?: __NAMESPACE__.IStandardElementFieldsArgs;
    tableTypeData?: __NAMESPACE__.IStandardElementFieldsArgs;
    witnessTypeData?: __NAMESPACE__.IWitnessElementFieldsArgs;
    richLinkTypeData?: __NAMESPACE__.IRichLinkElementFieldsArgs;
    membershipTypeData?: __NAMESPACE__.IMembershipElementFieldsArgs;
    embedTypeData?: __NAMESPACE__.IEmbedElementFieldsArgs;
    instagramTypeData?: __NAMESPACE__.IInstagramElementFieldsArgs;
    commentTypeData?: __NAMESPACE__.ICommentElementFieldsArgs;
    vineTypeData?: __NAMESPACE__.IVineElementFieldsArgs;
    contentAtomTypeData?: __NAMESPACE__.IContentAtomElementFieldsArgs;
}
export const BlockElementCodec: thrift.IStructCodec<IBlockElementArgs, IBlockElement> = {
    encode(args: IBlockElementArgs, output: thrift.TProtocol): void {
        const obj = {
            type: args.type,
            assets: args.assets,
            textTypeData: args.textTypeData,
            videoTypeData: args.videoTypeData,
            tweetTypeData: args.tweetTypeData,
            imageTypeData: args.imageTypeData,
            audioTypeData: args.audioTypeData,
            pullquoteTypeData: args.pullquoteTypeData,
            interactiveTypeData: args.interactiveTypeData,
            mapTypeData: args.mapTypeData,
            documentTypeData: args.documentTypeData,
            tableTypeData: args.tableTypeData,
            witnessTypeData: args.witnessTypeData,
            richLinkTypeData: args.richLinkTypeData,
            membershipTypeData: args.membershipTypeData,
            embedTypeData: args.embedTypeData,
            instagramTypeData: args.instagramTypeData,
            commentTypeData: args.commentTypeData,
            vineTypeData: args.vineTypeData,
            contentAtomTypeData: args.contentAtomTypeData
        };
        output.writeStructBegin("BlockElement");
        if (obj.type != null) {
            output.writeFieldBegin("type", thrift.TType.I32, 1);
            output.writeI32(obj.type);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[type] is unset!");
        }
        if (obj.assets != null) {
            output.writeFieldBegin("assets", thrift.TType.LIST, 2);
            output.writeListBegin(thrift.TType.STRUCT, obj.assets.length);
            obj.assets.forEach((value_1: __NAMESPACE__.IAssetArgs): void => {
                __NAMESPACE__.AssetCodec.encode(value_1, output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[assets] is unset!");
        }
        if (obj.textTypeData != null) {
            output.writeFieldBegin("textTypeData", thrift.TType.STRUCT, 3);
            __NAMESPACE__.TextElementFieldsCodec.encode(obj.textTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.videoTypeData != null) {
            output.writeFieldBegin("videoTypeData", thrift.TType.STRUCT, 4);
            __NAMESPACE__.VideoElementFieldsCodec.encode(obj.videoTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.tweetTypeData != null) {
            output.writeFieldBegin("tweetTypeData", thrift.TType.STRUCT, 5);
            __NAMESPACE__.TweetElementFieldsCodec.encode(obj.tweetTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.imageTypeData != null) {
            output.writeFieldBegin("imageTypeData", thrift.TType.STRUCT, 6);
            __NAMESPACE__.ImageElementFieldsCodec.encode(obj.imageTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.audioTypeData != null) {
            output.writeFieldBegin("audioTypeData", thrift.TType.STRUCT, 7);
            __NAMESPACE__.AudioElementFieldsCodec.encode(obj.audioTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.pullquoteTypeData != null) {
            output.writeFieldBegin("pullquoteTypeData", thrift.TType.STRUCT, 8);
            __NAMESPACE__.PullquoteElementFieldsCodec.encode(obj.pullquoteTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.interactiveTypeData != null) {
            output.writeFieldBegin("interactiveTypeData", thrift.TType.STRUCT, 9);
            __NAMESPACE__.InteractiveElementFieldsCodec.encode(obj.interactiveTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.mapTypeData != null) {
            output.writeFieldBegin("mapTypeData", thrift.TType.STRUCT, 10);
            __NAMESPACE__.StandardElementFieldsCodec.encode(obj.mapTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.documentTypeData != null) {
            output.writeFieldBegin("documentTypeData", thrift.TType.STRUCT, 11);
            __NAMESPACE__.StandardElementFieldsCodec.encode(obj.documentTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.tableTypeData != null) {
            output.writeFieldBegin("tableTypeData", thrift.TType.STRUCT, 12);
            __NAMESPACE__.StandardElementFieldsCodec.encode(obj.tableTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.witnessTypeData != null) {
            output.writeFieldBegin("witnessTypeData", thrift.TType.STRUCT, 13);
            __NAMESPACE__.WitnessElementFieldsCodec.encode(obj.witnessTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.richLinkTypeData != null) {
            output.writeFieldBegin("richLinkTypeData", thrift.TType.STRUCT, 14);
            __NAMESPACE__.RichLinkElementFieldsCodec.encode(obj.richLinkTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.membershipTypeData != null) {
            output.writeFieldBegin("membershipTypeData", thrift.TType.STRUCT, 15);
            __NAMESPACE__.MembershipElementFieldsCodec.encode(obj.membershipTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.embedTypeData != null) {
            output.writeFieldBegin("embedTypeData", thrift.TType.STRUCT, 16);
            __NAMESPACE__.EmbedElementFieldsCodec.encode(obj.embedTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.instagramTypeData != null) {
            output.writeFieldBegin("instagramTypeData", thrift.TType.STRUCT, 17);
            __NAMESPACE__.InstagramElementFieldsCodec.encode(obj.instagramTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.commentTypeData != null) {
            output.writeFieldBegin("commentTypeData", thrift.TType.STRUCT, 18);
            __NAMESPACE__.CommentElementFieldsCodec.encode(obj.commentTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.vineTypeData != null) {
            output.writeFieldBegin("vineTypeData", thrift.TType.STRUCT, 19);
            __NAMESPACE__.VineElementFieldsCodec.encode(obj.vineTypeData, output);
            output.writeFieldEnd();
        }
        if (obj.contentAtomTypeData != null) {
            output.writeFieldBegin("contentAtomTypeData", thrift.TType.STRUCT, 20);
            __NAMESPACE__.ContentAtomElementFieldsCodec.encode(obj.contentAtomTypeData, output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IBlockElement {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: __NAMESPACE__.ElementType = input.readI32();
                        _args.type = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.LIST) {
                        const value_3: Array<__NAMESPACE__.IAsset> = new Array<__NAMESPACE__.IAsset>();
                        const metadata_1: thrift.IThriftList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: __NAMESPACE__.IAsset = __NAMESPACE__.AssetCodec.decode(input);
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.assets = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_5: __NAMESPACE__.ITextElementFields = __NAMESPACE__.TextElementFieldsCodec.decode(input);
                        _args.textTypeData = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_6: __NAMESPACE__.IVideoElementFields = __NAMESPACE__.VideoElementFieldsCodec.decode(input);
                        _args.videoTypeData = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_7: __NAMESPACE__.ITweetElementFields = __NAMESPACE__.TweetElementFieldsCodec.decode(input);
                        _args.tweetTypeData = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_8: __NAMESPACE__.IImageElementFields = __NAMESPACE__.ImageElementFieldsCodec.decode(input);
                        _args.imageTypeData = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_9: __NAMESPACE__.IAudioElementFields = __NAMESPACE__.AudioElementFieldsCodec.decode(input);
                        _args.audioTypeData = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_10: __NAMESPACE__.IPullquoteElementFields = __NAMESPACE__.PullquoteElementFieldsCodec.decode(input);
                        _args.pullquoteTypeData = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_11: __NAMESPACE__.IInteractiveElementFields = __NAMESPACE__.InteractiveElementFieldsCodec.decode(input);
                        _args.interactiveTypeData = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_12: __NAMESPACE__.IStandardElementFields = __NAMESPACE__.StandardElementFieldsCodec.decode(input);
                        _args.mapTypeData = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_13: __NAMESPACE__.IStandardElementFields = __NAMESPACE__.StandardElementFieldsCodec.decode(input);
                        _args.documentTypeData = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_14: __NAMESPACE__.IStandardElementFields = __NAMESPACE__.StandardElementFieldsCodec.decode(input);
                        _args.tableTypeData = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_15: __NAMESPACE__.IWitnessElementFields = __NAMESPACE__.WitnessElementFieldsCodec.decode(input);
                        _args.witnessTypeData = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_16: __NAMESPACE__.IRichLinkElementFields = __NAMESPACE__.RichLinkElementFieldsCodec.decode(input);
                        _args.richLinkTypeData = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_17: __NAMESPACE__.IMembershipElementFields = __NAMESPACE__.MembershipElementFieldsCodec.decode(input);
                        _args.membershipTypeData = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_18: __NAMESPACE__.IEmbedElementFields = __NAMESPACE__.EmbedElementFieldsCodec.decode(input);
                        _args.embedTypeData = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_19: __NAMESPACE__.IInstagramElementFields = __NAMESPACE__.InstagramElementFieldsCodec.decode(input);
                        _args.instagramTypeData = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_20: __NAMESPACE__.ICommentElementFields = __NAMESPACE__.CommentElementFieldsCodec.decode(input);
                        _args.commentTypeData = value_20;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 19:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_21: __NAMESPACE__.IVineElementFields = __NAMESPACE__.VineElementFieldsCodec.decode(input);
                        _args.vineTypeData = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 20:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_22: __NAMESPACE__.IContentAtomElementFields = __NAMESPACE__.ContentAtomElementFieldsCodec.decode(input);
                        _args.contentAtomTypeData = value_22;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.type !== undefined && _args.assets !== undefined) {
            return {
                type: _args.type,
                assets: _args.assets,
                textTypeData: _args.textTypeData,
                videoTypeData: _args.videoTypeData,
                tweetTypeData: _args.tweetTypeData,
                imageTypeData: _args.imageTypeData,
                audioTypeData: _args.audioTypeData,
                pullquoteTypeData: _args.pullquoteTypeData,
                interactiveTypeData: _args.interactiveTypeData,
                mapTypeData: _args.mapTypeData,
                documentTypeData: _args.documentTypeData,
                tableTypeData: _args.tableTypeData,
                witnessTypeData: _args.witnessTypeData,
                richLinkTypeData: _args.richLinkTypeData,
                membershipTypeData: _args.membershipTypeData,
                embedTypeData: _args.embedTypeData,
                instagramTypeData: _args.instagramTypeData,
                commentTypeData: _args.commentTypeData,
                vineTypeData: _args.vineTypeData,
                contentAtomTypeData: _args.contentAtomTypeData
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read BlockElement from input");
        }
    }
};
export class BlockElement extends thrift.StructLike implements IBlockElement {
    public type: __NAMESPACE__.ElementType;
    public assets: Array<__NAMESPACE__.IAsset>;
    public textTypeData?: __NAMESPACE__.ITextElementFields;
    public videoTypeData?: __NAMESPACE__.IVideoElementFields;
    public tweetTypeData?: __NAMESPACE__.ITweetElementFields;
    public imageTypeData?: __NAMESPACE__.IImageElementFields;
    public audioTypeData?: __NAMESPACE__.IAudioElementFields;
    public pullquoteTypeData?: __NAMESPACE__.IPullquoteElementFields;
    public interactiveTypeData?: __NAMESPACE__.IInteractiveElementFields;
    public mapTypeData?: __NAMESPACE__.IStandardElementFields;
    public documentTypeData?: __NAMESPACE__.IStandardElementFields;
    public tableTypeData?: __NAMESPACE__.IStandardElementFields;
    public witnessTypeData?: __NAMESPACE__.IWitnessElementFields;
    public richLinkTypeData?: __NAMESPACE__.IRichLinkElementFields;
    public membershipTypeData?: __NAMESPACE__.IMembershipElementFields;
    public embedTypeData?: __NAMESPACE__.IEmbedElementFields;
    public instagramTypeData?: __NAMESPACE__.IInstagramElementFields;
    public commentTypeData?: __NAMESPACE__.ICommentElementFields;
    public vineTypeData?: __NAMESPACE__.IVineElementFields;
    public contentAtomTypeData?: __NAMESPACE__.IContentAtomElementFields;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IBlockElementArgs) {
        super();
        if (args.type != null) {
            const value_23: __NAMESPACE__.ElementType = args.type;
            this.type = value_23;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[type] is unset!");
        }
        if (args.assets != null) {
            const value_24: Array<__NAMESPACE__.IAsset> = new Array<__NAMESPACE__.IAsset>();
            args.assets.forEach((value_43: __NAMESPACE__.IAssetArgs): void => {
                const value_44: __NAMESPACE__.IAsset = new __NAMESPACE__.Asset(value_43);
                value_24.push(value_44);
            });
            this.assets = value_24;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[assets] is unset!");
        }
        if (args.textTypeData != null) {
            const value_25: __NAMESPACE__.ITextElementFields = new __NAMESPACE__.TextElementFields(args.textTypeData);
            this.textTypeData = value_25;
        }
        if (args.videoTypeData != null) {
            const value_26: __NAMESPACE__.IVideoElementFields = new __NAMESPACE__.VideoElementFields(args.videoTypeData);
            this.videoTypeData = value_26;
        }
        if (args.tweetTypeData != null) {
            const value_27: __NAMESPACE__.ITweetElementFields = new __NAMESPACE__.TweetElementFields(args.tweetTypeData);
            this.tweetTypeData = value_27;
        }
        if (args.imageTypeData != null) {
            const value_28: __NAMESPACE__.IImageElementFields = new __NAMESPACE__.ImageElementFields(args.imageTypeData);
            this.imageTypeData = value_28;
        }
        if (args.audioTypeData != null) {
            const value_29: __NAMESPACE__.IAudioElementFields = new __NAMESPACE__.AudioElementFields(args.audioTypeData);
            this.audioTypeData = value_29;
        }
        if (args.pullquoteTypeData != null) {
            const value_30: __NAMESPACE__.IPullquoteElementFields = new __NAMESPACE__.PullquoteElementFields(args.pullquoteTypeData);
            this.pullquoteTypeData = value_30;
        }
        if (args.interactiveTypeData != null) {
            const value_31: __NAMESPACE__.IInteractiveElementFields = new __NAMESPACE__.InteractiveElementFields(args.interactiveTypeData);
            this.interactiveTypeData = value_31;
        }
        if (args.mapTypeData != null) {
            const value_32: __NAMESPACE__.IStandardElementFields = new __NAMESPACE__.StandardElementFields(args.mapTypeData);
            this.mapTypeData = value_32;
        }
        if (args.documentTypeData != null) {
            const value_33: __NAMESPACE__.IStandardElementFields = new __NAMESPACE__.StandardElementFields(args.documentTypeData);
            this.documentTypeData = value_33;
        }
        if (args.tableTypeData != null) {
            const value_34: __NAMESPACE__.IStandardElementFields = new __NAMESPACE__.StandardElementFields(args.tableTypeData);
            this.tableTypeData = value_34;
        }
        if (args.witnessTypeData != null) {
            const value_35: __NAMESPACE__.IWitnessElementFields = new __NAMESPACE__.WitnessElementFields(args.witnessTypeData);
            this.witnessTypeData = value_35;
        }
        if (args.richLinkTypeData != null) {
            const value_36: __NAMESPACE__.IRichLinkElementFields = new __NAMESPACE__.RichLinkElementFields(args.richLinkTypeData);
            this.richLinkTypeData = value_36;
        }
        if (args.membershipTypeData != null) {
            const value_37: __NAMESPACE__.IMembershipElementFields = new __NAMESPACE__.MembershipElementFields(args.membershipTypeData);
            this.membershipTypeData = value_37;
        }
        if (args.embedTypeData != null) {
            const value_38: __NAMESPACE__.IEmbedElementFields = new __NAMESPACE__.EmbedElementFields(args.embedTypeData);
            this.embedTypeData = value_38;
        }
        if (args.instagramTypeData != null) {
            const value_39: __NAMESPACE__.IInstagramElementFields = new __NAMESPACE__.InstagramElementFields(args.instagramTypeData);
            this.instagramTypeData = value_39;
        }
        if (args.commentTypeData != null) {
            const value_40: __NAMESPACE__.ICommentElementFields = new __NAMESPACE__.CommentElementFields(args.commentTypeData);
            this.commentTypeData = value_40;
        }
        if (args.vineTypeData != null) {
            const value_41: __NAMESPACE__.IVineElementFields = new __NAMESPACE__.VineElementFields(args.vineTypeData);
            this.vineTypeData = value_41;
        }
        if (args.contentAtomTypeData != null) {
            const value_42: __NAMESPACE__.IContentAtomElementFields = new __NAMESPACE__.ContentAtomElementFields(args.contentAtomTypeData);
            this.contentAtomTypeData = value_42;
        }
    }
    public static read(input: thrift.TProtocol): BlockElement {
        return new BlockElement(BlockElementCodec.decode(input));
    }
    public static write(args: IBlockElementArgs, output: thrift.TProtocol): void {
        return BlockElementCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return BlockElementCodec.encode(this, output);
    }
}
