/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as com_gu_story_model_v1 from "./com/gu/story/model/v1";
export interface IStoriesResponse {
    status: string;
    total: number;
    results: Array<com_gu_story_model_v1.IStory>;
}
export interface IStoriesResponseArgs {
    status: string;
    total: number;
    results: Array<com_gu_story_model_v1.IStoryArgs>;
}
export const StoriesResponseCodec: thrift.IStructCodec<IStoriesResponseArgs, IStoriesResponse> = {
    encode(args: IStoriesResponseArgs, output: thrift.TProtocol): void {
        const obj = {
            status: args.status,
            total: args.total,
            results: args.results
        };
        output.writeStructBegin("StoriesResponse");
        if (obj.status != null) {
            output.writeFieldBegin("status", thrift.TType.STRING, 1);
            output.writeString(obj.status);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[status] is unset!");
        }
        if (obj.total != null) {
            output.writeFieldBegin("total", thrift.TType.I32, 2);
            output.writeI32(obj.total);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[total] is unset!");
        }
        if (obj.results != null) {
            output.writeFieldBegin("results", thrift.TType.LIST, 3);
            output.writeListBegin(thrift.TType.STRUCT, obj.results.length);
            obj.results.forEach((value_1: com_gu_story_model_v1.IStoryArgs): void => {
                com_gu_story_model_v1.StoryCodec.encode(value_1, output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[results] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IStoriesResponse {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.status = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_3: number = input.readI32();
                        _args.total = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.LIST) {
                        const value_4: Array<com_gu_story_model_v1.IStory> = new Array<com_gu_story_model_v1.IStory>();
                        const metadata_1: thrift.IThriftList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_5: com_gu_story_model_v1.IStory = com_gu_story_model_v1.StoryCodec.decode(input);
                            value_4.push(value_5);
                        }
                        input.readListEnd();
                        _args.results = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.status !== undefined && _args.total !== undefined && _args.results !== undefined) {
            return {
                status: _args.status,
                total: _args.total,
                results: _args.results
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read StoriesResponse from input");
        }
    }
};
export class StoriesResponse extends thrift.StructLike implements IStoriesResponse {
    public status: string;
    public total: number;
    public results: Array<com_gu_story_model_v1.IStory>;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IStoriesResponseArgs) {
        super();
        if (args.status != null) {
            const value_6: string = args.status;
            this.status = value_6;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[status] is unset!");
        }
        if (args.total != null) {
            const value_7: number = args.total;
            this.total = value_7;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[total] is unset!");
        }
        if (args.results != null) {
            const value_8: Array<com_gu_story_model_v1.IStory> = new Array<com_gu_story_model_v1.IStory>();
            args.results.forEach((value_9: com_gu_story_model_v1.IStoryArgs): void => {
                const value_10: com_gu_story_model_v1.IStory = new com_gu_story_model_v1.Story(value_9);
                value_8.push(value_10);
            });
            this.results = value_8;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[results] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): StoriesResponse {
        return new StoriesResponse(StoriesResponseCodec.decode(input));
    }
    public static write(args: IStoriesResponseArgs, output: thrift.TProtocol): void {
        return StoriesResponseCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return StoriesResponseCodec.encode(this, output);
    }
}
