/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum ArticleType {
    Article = 1,
    Snap = 2
}
export enum Group {
    Included = 1,
    Linked = 2
}
