/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum AtomType {
    QUIZ = 0,
    MEDIA = 2,
    EXPLAINER = 3,
    CTA = 4,
    INTERACTIVE = 5,
    REVIEW = 6,
    RECIPE = 7,
    STORYQUESTIONS = 8,
    QANDA = 9,
    PROFILE = 10,
    GUIDE = 11,
    TIMELINE = 12,
    COMMONSDIVISION = 13,
    CHART = 14,
    AUDIO = 15
}
export enum EventType {
    UPDATE = 0,
    TAKEDOWN = 1
}
