/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as __NAMESPACE__ from "./.";
export interface IChartAtom {
    chartType: __NAMESPACE__.ChartType;
    furniture: __NAMESPACE__.IFurniture;
    tabularData: __NAMESPACE__.ITabularData;
    seriesColour: Array<__NAMESPACE__.ISeriesColour>;
    displaySettings: __NAMESPACE__.IDisplaySettings;
    hiddenColumns?: Array<number>;
    hiddenRows?: Array<number>;
    xAxis?: __NAMESPACE__.IAxis;
    yAxis?: __NAMESPACE__.IAxis;
}
export interface IChartAtomArgs {
    chartType: __NAMESPACE__.ChartType;
    furniture: __NAMESPACE__.IFurnitureArgs;
    tabularData: __NAMESPACE__.ITabularDataArgs;
    seriesColour: Array<__NAMESPACE__.ISeriesColourArgs>;
    displaySettings: __NAMESPACE__.IDisplaySettingsArgs;
    hiddenColumns?: Array<number>;
    hiddenRows?: Array<number>;
    xAxis?: __NAMESPACE__.IAxisArgs;
    yAxis?: __NAMESPACE__.IAxisArgs;
}
export const ChartAtomCodec: thrift.IStructCodec<IChartAtomArgs, IChartAtom> = {
    encode(args: IChartAtomArgs, output: thrift.TProtocol): void {
        const obj = {
            chartType: args.chartType,
            furniture: args.furniture,
            tabularData: args.tabularData,
            seriesColour: args.seriesColour,
            displaySettings: args.displaySettings,
            hiddenColumns: args.hiddenColumns,
            hiddenRows: args.hiddenRows,
            xAxis: args.xAxis,
            yAxis: args.yAxis
        };
        output.writeStructBegin("ChartAtom");
        if (obj.chartType != null) {
            output.writeFieldBegin("chartType", thrift.TType.I32, 1);
            output.writeI32(obj.chartType);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[chartType] is unset!");
        }
        if (obj.furniture != null) {
            output.writeFieldBegin("furniture", thrift.TType.STRUCT, 2);
            __NAMESPACE__.FurnitureCodec.encode(obj.furniture, output);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[furniture] is unset!");
        }
        if (obj.tabularData != null) {
            output.writeFieldBegin("tabularData", thrift.TType.STRUCT, 3);
            __NAMESPACE__.TabularDataCodec.encode(obj.tabularData, output);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[tabularData] is unset!");
        }
        if (obj.seriesColour != null) {
            output.writeFieldBegin("seriesColour", thrift.TType.LIST, 4);
            output.writeListBegin(thrift.TType.STRUCT, obj.seriesColour.length);
            obj.seriesColour.forEach((value_1: __NAMESPACE__.ISeriesColourArgs): void => {
                __NAMESPACE__.SeriesColourCodec.encode(value_1, output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[seriesColour] is unset!");
        }
        if (obj.displaySettings != null) {
            output.writeFieldBegin("displaySettings", thrift.TType.STRUCT, 5);
            __NAMESPACE__.DisplaySettingsCodec.encode(obj.displaySettings, output);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[displaySettings] is unset!");
        }
        if (obj.hiddenColumns != null) {
            output.writeFieldBegin("hiddenColumns", thrift.TType.LIST, 6);
            output.writeListBegin(thrift.TType.I32, obj.hiddenColumns.length);
            obj.hiddenColumns.forEach((value_2: number): void => {
                output.writeI32(value_2);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (obj.hiddenRows != null) {
            output.writeFieldBegin("hiddenRows", thrift.TType.LIST, 7);
            output.writeListBegin(thrift.TType.I32, obj.hiddenRows.length);
            obj.hiddenRows.forEach((value_3: number): void => {
                output.writeI32(value_3);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (obj.xAxis != null) {
            output.writeFieldBegin("xAxis", thrift.TType.STRUCT, 8);
            __NAMESPACE__.AxisCodec.encode(obj.xAxis, output);
            output.writeFieldEnd();
        }
        if (obj.yAxis != null) {
            output.writeFieldBegin("yAxis", thrift.TType.STRUCT, 9);
            __NAMESPACE__.AxisCodec.encode(obj.yAxis, output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IChartAtom {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_4: __NAMESPACE__.ChartType = input.readI32();
                        _args.chartType = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_5: __NAMESPACE__.IFurniture = __NAMESPACE__.FurnitureCodec.decode(input);
                        _args.furniture = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_6: __NAMESPACE__.ITabularData = __NAMESPACE__.TabularDataCodec.decode(input);
                        _args.tabularData = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.LIST) {
                        const value_7: Array<__NAMESPACE__.ISeriesColour> = new Array<__NAMESPACE__.ISeriesColour>();
                        const metadata_1: thrift.IThriftList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_8: __NAMESPACE__.ISeriesColour = __NAMESPACE__.SeriesColourCodec.decode(input);
                            value_7.push(value_8);
                        }
                        input.readListEnd();
                        _args.seriesColour = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_9: __NAMESPACE__.IDisplaySettings = __NAMESPACE__.DisplaySettingsCodec.decode(input);
                        _args.displaySettings = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.TType.LIST) {
                        const value_10: Array<number> = new Array<number>();
                        const metadata_2: thrift.IThriftList = input.readListBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const value_11: number = input.readI32();
                            value_10.push(value_11);
                        }
                        input.readListEnd();
                        _args.hiddenColumns = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.TType.LIST) {
                        const value_12: Array<number> = new Array<number>();
                        const metadata_3: thrift.IThriftList = input.readListBegin();
                        const size_3: number = metadata_3.size;
                        for (let i_3: number = 0; i_3 < size_3; i_3++) {
                            const value_13: number = input.readI32();
                            value_12.push(value_13);
                        }
                        input.readListEnd();
                        _args.hiddenRows = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_14: __NAMESPACE__.IAxis = __NAMESPACE__.AxisCodec.decode(input);
                        _args.xAxis = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_15: __NAMESPACE__.IAxis = __NAMESPACE__.AxisCodec.decode(input);
                        _args.yAxis = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.chartType !== undefined && _args.furniture !== undefined && _args.tabularData !== undefined && _args.seriesColour !== undefined && _args.displaySettings !== undefined) {
            return {
                chartType: _args.chartType,
                furniture: _args.furniture,
                tabularData: _args.tabularData,
                seriesColour: _args.seriesColour,
                displaySettings: _args.displaySettings,
                hiddenColumns: _args.hiddenColumns,
                hiddenRows: _args.hiddenRows,
                xAxis: _args.xAxis,
                yAxis: _args.yAxis
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read ChartAtom from input");
        }
    }
};
export class ChartAtom extends thrift.StructLike implements IChartAtom {
    public chartType: __NAMESPACE__.ChartType;
    public furniture: __NAMESPACE__.IFurniture;
    public tabularData: __NAMESPACE__.ITabularData;
    public seriesColour: Array<__NAMESPACE__.ISeriesColour>;
    public displaySettings: __NAMESPACE__.IDisplaySettings;
    public hiddenColumns?: Array<number>;
    public hiddenRows?: Array<number>;
    public xAxis?: __NAMESPACE__.IAxis;
    public yAxis?: __NAMESPACE__.IAxis;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IChartAtomArgs) {
        super();
        if (args.chartType != null) {
            const value_16: __NAMESPACE__.ChartType = args.chartType;
            this.chartType = value_16;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[chartType] is unset!");
        }
        if (args.furniture != null) {
            const value_17: __NAMESPACE__.IFurniture = new __NAMESPACE__.Furniture(args.furniture);
            this.furniture = value_17;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[furniture] is unset!");
        }
        if (args.tabularData != null) {
            const value_18: __NAMESPACE__.ITabularData = new __NAMESPACE__.TabularData(args.tabularData);
            this.tabularData = value_18;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[tabularData] is unset!");
        }
        if (args.seriesColour != null) {
            const value_19: Array<__NAMESPACE__.ISeriesColour> = new Array<__NAMESPACE__.ISeriesColour>();
            args.seriesColour.forEach((value_25: __NAMESPACE__.ISeriesColourArgs): void => {
                const value_26: __NAMESPACE__.ISeriesColour = new __NAMESPACE__.SeriesColour(value_25);
                value_19.push(value_26);
            });
            this.seriesColour = value_19;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[seriesColour] is unset!");
        }
        if (args.displaySettings != null) {
            const value_20: __NAMESPACE__.IDisplaySettings = new __NAMESPACE__.DisplaySettings(args.displaySettings);
            this.displaySettings = value_20;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[displaySettings] is unset!");
        }
        if (args.hiddenColumns != null) {
            const value_21: Array<number> = new Array<number>();
            args.hiddenColumns.forEach((value_27: number): void => {
                const value_28: number = value_27;
                value_21.push(value_28);
            });
            this.hiddenColumns = value_21;
        }
        if (args.hiddenRows != null) {
            const value_22: Array<number> = new Array<number>();
            args.hiddenRows.forEach((value_29: number): void => {
                const value_30: number = value_29;
                value_22.push(value_30);
            });
            this.hiddenRows = value_22;
        }
        if (args.xAxis != null) {
            const value_23: __NAMESPACE__.IAxis = new __NAMESPACE__.Axis(args.xAxis);
            this.xAxis = value_23;
        }
        if (args.yAxis != null) {
            const value_24: __NAMESPACE__.IAxis = new __NAMESPACE__.Axis(args.yAxis);
            this.yAxis = value_24;
        }
    }
    public static read(input: thrift.TProtocol): ChartAtom {
        return new ChartAtom(ChartAtomCodec.decode(input));
    }
    public static write(args: IChartAtomArgs, output: thrift.TProtocol): void {
        return ChartAtomCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return ChartAtomCodec.encode(this, output);
    }
}
