/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum ChartType {
    BAR = 0
}
export enum RowType {
    STRING = 0,
    DATE = 1
}
