/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
export enum ContentType {
  ARTICLE = 0,
  LIVEBLOG = 1,
  GALLERY = 2,
  INTERACTIVE = 3,
  PICTURE = 4,
  VIDEO = 5,
  CROSSWORD = 6,
  AUDIO = 7,
}
export enum ElementType {
  TEXT = 0,
  IMAGE = 1,
  EMBED = 2,
  FORM = 3,
  PULLQUOTE = 4,
  INTERACTIVE = 5,
  COMMENT = 6,
  RICH_LINK = 7,
  TABLE = 8,
  VIDEO = 9,
  TWEET = 10,
  WITNESS = 11,
  CODE = 12,
  AUDIO = 13,
  MAP = 14,
  DOCUMENT = 15,
  MEMBERSHIP = 16,
  INSTAGRAM = 17,
  CONTENTATOM = 18,
  VINE = 19,
}
export enum TagType {
  CONTRIBUTOR = 0,
  KEYWORD = 1,
  SERIES = 2,
  NEWSPAPER_BOOK_SECTION = 3,
  NEWSPAPER_BOOK = 4,
  BLOG = 5,
  TONE = 6,
  TYPE = 7,
  PUBLICATION = 8,
  TRACKING = 9,
  PAID_CONTENT = 10,
  CAMPAIGN = 11,
}
export enum CrosswordType {
  QUICK = 0,
  CRYPTIC = 1,
  QUIPTIC = 2,
  SPEEDY = 3,
  PRIZE = 4,
  EVERYMAN = 5,
  DIAN_QUIPTIC_CROSSWORD = 6,
  WEEKEND = 7,
}
export enum Office {
  UK = 0,
  US = 1,
  AUS = 2,
}
export enum AssetType {
  IMAGE = 0,
  VIDEO = 1,
  AUDIO = 2,
  EMBED = 3,
  TWEET = 4,
}
export enum MembershipTier {
  MEMBERS_ONLY = 0,
  PAID_MEMBERS_ONLY = 1,
}
export enum SponsorshipType {
  SPONSORED = 0,
  FOUNDATION = 1,
  PAID_CONTENT = 2,
}
