/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.5.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as __NAMESPACE__ from "./.";
export interface IContent {
    id: string;
    type: __NAMESPACE__.ContentType;
}
export interface IContentArgs {
    id: string;
    type: __NAMESPACE__.ContentType;
}
export const ContentCodec: thrift.IStructCodec<IContentArgs, IContent> = {
    encode(args: IContentArgs, output: thrift.TProtocol): void {
        const obj = {
            id: args.id,
            type: args.type
        };
        output.writeStructBegin("Content");
        if (obj.id != null) {
            output.writeFieldBegin("id", thrift.TType.STRING, 1);
            output.writeString(obj.id);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[id] is unset!");
        }
        if (obj.type != null) {
            output.writeFieldBegin("type", thrift.TType.I32, 2);
            output.writeI32(obj.type);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[type] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IContent {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: __NAMESPACE__.ContentType = input.readI32();
                        _args.type = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.id !== undefined && _args.type !== undefined) {
            return {
                id: _args.id,
                type: _args.type
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read Content from input");
        }
    }
};
export class Content extends thrift.StructLike implements IContent {
    public id: string;
    public type: __NAMESPACE__.ContentType;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IContentArgs) {
        super();
        if (args.id != null) {
            const value_3: string = args.id;
            this.id = value_3;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[id] is unset!");
        }
        if (args.type != null) {
            const value_4: __NAMESPACE__.ContentType = args.type;
            this.type = value_4;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[type] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): Content {
        return new Content(ContentCodec.decode(input));
    }
    public static write(args: IContentArgs, output: thrift.TProtocol): void {
        return ContentCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return ContentCodec.encode(this, output);
    }
}
